### ISSUE TITLE
solving problem while building the whitepaper

### ISSUE THREAD

**Issue by franklee00** [HalalChain/whitepaper#29]
tlmgr option repository http://mirror.ctan.org/systems/texlive/tlnet

**Comment by dindinw** [comment]
Please see the latest installation guide (https://github.com/HalalChain/whitepaper/#download-and-install) & install the MacTeX 2019 to avoid using tlmgr

**Comment by franklee00** [comment]
Yes, I did that in about 3:00 am in the 30th of June 2019, and that worked. The whitepaper has been maked successfully.
